export const SalesProductData = [
  {
    id: "1",
    img: "/product01.png",
    title: "Bought Together",
    alt: "sales product img1",
    badgeTitle: "-5%",
    price: 250,
    reviews: [
      {
        id: "1",
        author: "Alice",
        rating: 5,
        comment: "Great product!",
        post: [
          {
            name: "john",
            stress: [
              {
                level: "john Stress",
                relief: [
                  {
                    name: "john relief",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "2",
    img: "/product02.png",
    title: "Dining Chair",
    alt: "sales product img2",
    badgeTitle: "-16%",
    price: 500,
    post: [{ name: "john" }],
  },
  {
    id: "3",
    img: "/product03.png",
    title: "Domino Chair",
    alt: "sales product img3",
    badgeTitle: "",
    price: 300,
    post: [{ name: "john" }],
  },
  {
    id: "4",
    img: "/product04.png",
    title: "Domino Chair",
    alt: "sales product img4",
    badgeTitle: "-20%",
    price: 150,
    post: [{ name: "john" }],
  },
  {
    id: "5",
    img: "/product05.png",
    title: "Domino House",
    alt: "sales product img5",
    badgeTitle: "",
    price: 500,
    post: [{ name: "john" }],
  },
  {
    id: "6",
    img: "/product06.png",
    title: "Jeri Chair",
    alt: "sales product img6",
    badgeTitle: "-10%",
    price: 400,
    post: [{ name: "john" }],
  },
  {
    id: "7",
    img: "/product02.png",
    title: "Jeri Dining",
    alt: "sales product img2",
    badgeTitle: "",
    price: 250,
    post: [{ name: "john" }],
  },
  {
    id: "8",
    img: "/product03.png",
    title: "Jeri Dining Chair",
    alt: "sales product img3",
    badgeTitle: "-10%",
    price: 240.0,
    post: [{ name: "john" }],
  },
];
