import './globals.css'
import { Poppins } from 'next/font/google'
import TopBar from '@/components/Layouts/TopBar'
import Header from '@/components/Layouts/Header'
import Footer from '@/components/Layouts/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: 'Furniture',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <TopBar />
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
